<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Veop</Authors>
    <PackageId>Termule.Templates</PackageId>
    <Description>The template pack for the Termule SDK.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>        
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/V30P/termule</RepositoryUrl>
    <PackageTags>terminal;console;games</PackageTags>
    <PackageType>Template</PackageType>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoDefaultExcludes>true</NoDefaultExcludes>
  </PropertyGroup>

  <!-- Stops NuGet from complaining about having no assemblies to pack -->
  <PropertyGroup>
    <NoWarn>NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="content\**\*" Exclude="content\**\bin\**;content\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
