<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>Termule.Demos</AssemblyName>
        <RootNamespace>Termule.Demos</RootNamespace>
        <PublishSingleFile>true</PublishSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Engine\Engine.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="res\**\*">
            <!-- Makes sure resource paths are the same on all systems -->
            <LogicalName>res/$([System.String]::Copy('%(RecursiveDir)%(Filename)%(Extension)').Replace('\', '/'))</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

    <!-- Stop StyleCop from requiring documentation -->
    <PropertyGroup>
        <NoWarn>$(NoWarn);SA0001</NoWarn>
    </PropertyGroup>

</Project>
